### ISSUE TITLE
period-named? has unexpected behavior

### ISSUE THREAD

**Issue by ToBeReplaced** [aredington/monotony#4]
`period-named?` sounds like it compares against a string, but it actually compares against a key.  Moreover, if you pass in a string, you get a NullPointerException.

The concept of a "named" period is a bit deceiving, because all you do is compare the value of the field at the start and end times.  For example:

``` clojure
(m/period-named? conf (first (m/periods conf :week)) :august)
;; true
```

I'm wondering if it's better to to offer something like:

``` clojure
(m/start-day-of-week conf period)
;; (.get (m/calendar conf (t/start period)) Calendar/DAY_OF_WEEK)
(= Calendar/SUNDAY (m/start-day-of-week conf period))
;; true
```

The thought would be to open up utility functions to go from periods to the calendar fields for the start and end instants.

What do you think?

**Comment by aredington** [comment]
Hey, thanks for the report!

It looks like there's a couple of issues rolled up in this: 

1) monotony.core/period-named? looks like it could accept a string, but only accepts keywords. When given a string it fails in a non-obvious manner. I think this one's relatively easy to fix, and that we can just accept strings, but it also highlights a failure mode of someone passing in a value for the period name that isn't recognized.

2) monotony.core/period-named? returns true when the period being scrutinized is smaller than the period implied by the name. E.g. august implies a period of exactly one month (Aug 1st 12:00:00.000AM to Aug 31st 11:59:59.999PM), but monotony.core/period-named? returns true when interrogating any period contained in that time frame.

The first issue is pretty trivial, I think extending support for strings is easy, and we can give a better error report than an NPE when the name doesn't make sense to monotony. I'll fix it soon.

The second has an interesting question: what is the value in returning false for period-named? when given one day in august, and :august? I don't think I understand your motivation for altering the semantics, what is the use case you're trying to make happen here? Maybe monotony can solve the problem in some other direction, or maybe we should discuss a new feature (and maybe it's exactly start-day-of-week as you propose) after identifying the core problem trying to be solved.

Thanks for the bug report! I'm looking forward to hearing more about how you're intending to use monotony.

**Comment by ToBeReplaced** [comment]
My use case is to construct a seq of non-overlapping intervals (periods) to indicate times when a service needs to be run.  Run X Monday through Friday, between 00:00-01:00 and 18:00-19:00, as well as on Saturday and Sunday from 15:00-17:00.

Right now, I use clj-time/joda-time.  In pseudo-code:

``` clojure
(->> (DateMidnight. (DateTimeZone/forID timezone))
     (iterate #(plus % (days 1)))
     (mapcat (fn [midnight] 
               (map #(make-into-an-hour-based-interval midnight %) 
                     (if (weekday? midnight) [[0 1] [18 19]] [[15 17]]))))))
```

Somewhere down the line, this hits a `ScheduledThreadPoolExecutor` that schedules the first interval, and triggers scheduling of the next interval on its completion.

Ordinarily, I would use Quartz for this, but I really liked the idea of decoupling the creation of intervals (or instants for that matter) from the process responsible for scheduling them, so I wanted to try it out.

The main reason I am not using monotony right now is that I haven't figured out what it buys me over the above joda-time based approach.  The usage of joda-time's Interval type is a plus for me.

In all, the above approach has been questionable, at best.  While it works, there's no visibility into the scheduling after it has begun, and it makes repl development a pain because we have an infinite seq being passed around.  In order to make this kind of thing more exciting to me, we would need to work on creating a data-based API.  Ex:

``` clojure
(period-seq {:timezone timezone
             :days [:monday :tuesday :wednesday :thursday :friday] 
             :hours [0 18] 
             :duration {:hours 1}}
            {:timezone timezone
             :days [:saturday :sunday]
             :hours [15]
             :duration {:hours 2}})
```

Clearly I haven't thought that through, but there might be some mileage there, and there are plenty of other projects that have tried it in other languages so there are lot of examples to learn from.

**Comment by aredington** [comment]
I see, so you want to use period-named? to differentiate if you'll be chopping up the day into 00:00-01:00 and 18:00-19:00, or 15:00-17:00.

Let me start off by saying that I really think Joda time is awesome and a great tool to work with for the problem domain that it solves. I don't think that's an empty claim, because I've weaved optional joda-time support into monotony (https://github.com/aredington/monotony/blob/master/src/monotony/time.clj#L52).

On the other hand I'd like to propose another construction of your schedule that works more in the realm of simple calculations combined into useful higher aggregates, and I think that you might find that it also illustrates the unique value that monotony presents:

We can, using monotony, generate an infinite lazy seq of weeks, and we can make it start on a clean break with

``` clojure
(m/periods conf :week (m/next-boundary conf :week))
```

This yields an infinite lazy sequence of weeks bounded on Sunday at midnight and Saturday immediately prior to midnight. Let's call this guy the-week-seq henceforth as it's gonna be used to generate two infinite lazy seqs of hour long periods: one for weekends, and one for weekdays. If we write two functions that operate against a single week, we can use that function to break down a week into the two different patterns for scheduling (weekdays and weekends), and mapcat the results of those two functions of the-week-seq to get two seqs of the schedules for weekdays and weekends independently. They might look something like this:

``` clojure
(defn weekday-hours
  [conf week]
  (->> (m/cycles-in conf week :day)
          rest ;; drop sunday
          but-last ;; drop saturday
          (mapcat weekday-hours-for-day)))
```

Where weekday-hours-for-day is a fn that takes a day and returns two periods out of that day corresponding to 00:00-01:00 and 18:00-19:00. We can use a similar fn for weekends, and we can get two seqs corresponding to the distinct schedules like so:

``` clojure
(def weekday-hours (map (partial weekday-hours conf) the-week-seq))
(def weekend-hours (map (partial weekend-hours conf) the-week-seq))
```

This lets us do our schedule generation in discrete chunks that aren't interleaved or tightly coupled, but we still don't have something we can schedule off of because they're totally separate. This is where I think monotony shines and distinguishes itself, to get our schedule we do the following:

``` clojure
(def schedule (m/combine weekday-hours weekend-hours))
```

And we're done. Schedule holds onto the seqs you give it, and gives you periods off the heads of those seqs such that you get them all in chronological order. Trying to tackle the problem in joda time as constructed above, you have to know about your two different cases down in your mapped fn. In monotony, you can solve each of the problems (weekday schedule and weekend schedule) in isolation, then merge them when you're confident in each.

Also keep in mind that in this half-way fleshed out proposal, there's no need to ever work with names for periods; we work with the regular numeric structure of time for dividing it up and arriving at the correct periods. I've left a lot of gaps in these code samples, but I hope it illustrates the idea I'm trying to express. If not let me know, and I can flesh it all the way out in a gist.

**Comment by ToBeReplaced** [comment]
Thanks.  I wanted to use `period-named` because I don't like: 

``` clojure
(mapcat weekend-hours-for-day [(first days) (last days)])
(->> days rest but-last (mapcat weekday-hours-for-day))
```

I think that the implicit knowledge that the week is ordered Sunday-Saturday is unnecessary overhead.  Here, I would filter on:

``` clojure
(some-fn #(period-named? conf % :monday) ...)
```

This is quite clunky though.  The dropping/selecting of which days corresponds to a weekend is too wrapped in implementation knowledge and needs to be more declarative.  Maybe what doesn't work for me is that I feel as though I want to think about start times first, then the periods.  Once I have a lazy-sequence of periods, I have to think differently to operate on them.

The use of a combine function is nice.  I use a more generic version of your combine function to do get the same effect: https://gist.github.com/ToBeReplaced/6193452 .  I do something like

``` clojure
(interleave-by clj-time.core/start [weekday-intervals weekend-intervals])
```

This lets me keep the different schedules segregated, and has the added benefit of allowing me to change the way I combine them (eg. when will the next task end?).

**Comment by aredington** [comment]
I can see that, it makes a lot of sense actually!

I'm thinking that something along the lines of period-name as a function that does a little contemplation of the span of the period input and then returns the appropriate keyword that names that period would be applicable, and then it would be possible to use a set as the predicate which is used for bisecting the series of days yielded into weekdays and weekends. The logic namespace already provides facilities for mapping an input period out to a cycle type, so it shouldn't be too difficult to invert out to the name for arbitrary periods.

I've pushed fixes for the failure behavior to master; period-named? now accepts strings as well as keywords, and throws an illegal argument exception if it has no clue what the tested name is.

**Comment by ToBeReplaced** [comment]
I thought about this some more... Looking at Joda and the JDK8 java.time, the different ways you can look at time are:

``` clojure
:chronology
:timezone
:eras
:centuries-of-era
:years-of-era
:years-of-century
:years
:weekyears
:months-of-year
:weeks-of-weekyear
:weeks-of-month
:days-of-year
:days-of-month
:days-of-week
:hours-of-day
:minutes-of-day
:minutes-of-hour
:seconds-of-day
:seconds-of-minute
:milliseconds-of-day
:milliseconds-of-second
```

I could imagine a data specification like:

``` clojure
;;; The first Wednesday of every month at 5:00 PM locally.
[:first-of :month {:day-of-week :wednesday :hour-of-day 17}]
;;; Every other hour at 5 minutes past the hour.
[:take-nth 2 {:minute-of-hour 5}] ; Not sensitive to DST and the like.
```

Not totally fleshed out, but it seems like there might be a way to define a "schedule specification" on top of EDN that could be a portable representation of a periodic schedule.  Then we could plug in implementations of it with Joda/java.time/python/whatever.  You'd also open up doors for someone to implement a way to go from such a specification to task scheduling.

**Comment by aredington** [comment]
I implemented period-name, which returns the keyword corresponding to a period's name. I then went and implemented your schedule in monotony as an example, and put it in a gist: https://gist.github.com/aredington/6320532

I think any DSL which will encompass the behavior monotony can support starts to approach a turing complete language. (e.g. plucking nth items from collections) As EDN is already a specification that is data, I'm not seeing a ton of value in building another DSL on top of it just yet. I could see some value in having a period generator which accepts an iCal stream as an input and returns a lazy seq of that iCal's schedule.

I'm gonna go ahead and close this issue, because it's getting far afield of the opening criteria of "period-named? does unexpected things"
